application: wired-victor-138322
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  max_idle_instances: 1  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

handlers:
- url: /favicon.ico
  static_files: static/appicons/favicon.ico
  upload: static/appicons/favicon.ico
  secure: always

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static
  secure: always

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application
  secure: always

- url: /static
  static_dir: PokemonWeb/static
  secure: always

- url: .*
  script: run.PokemonWeb.web.app
  secure: always
